homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

url_index:
    path:      /url
    defaults:  { _controller: AppBundle:Url:index }

url_export_yaml:
    path:      /url/export_yaml
    defaults:  { _controller: AppBundle:Url:exportYaml }

url_create:
    path:      /url/create
    defaults:  { _controller: AppBundle:Url:create }

url_update:
    path:      /url/update/{id}
    defaults:  { _controller: AppBundle:Url:update }

url_delete:
    path:      /url/delete/{id}
    defaults:  { _controller: AppBundle:Url:delete }

url_test:
    path:      /url/test
    defaults:  { _controller: AppBundle:Url:test }